export const superSkiCardResorts = [
  "Obertauern",
  "Bergbahnen Dachstein Salzkammergut",
  "Gastein",
  "Großarltal / Ski amadé",
  "Region Hochkönig / Ski amadé",
  "Abtenau",
  "KitzSki",
  "Naglköpfl",
  "Rauris",
  "Skicircus Saalbach Hinterglemm Leogang Fieberbrunn / ALPIN CARD",
  "Zell am See, Schmittenhöhe / ALPIN CARD",
  "Ski Juwel Alpbachtal Wildschönau",
  "SkiWelt Wilder Kaiser - Brixental",
  "Weissee Gletscherwelt",
  "Werfenweng",
  "Wildkogel-Arena",
  "Zillertal Arena",
  "Kitzsteinhorn & Maiskogel / ALPIN CARD",
  "3 Länder Freizeit-Arena",
  "Postalm Winterpark",
  "Salzburger Sportwelt / Ski amadé",
  "Region Schladming Dachstein / Ski amadé",
  "Schneebären",
  "Untersbergbahn",
  "Zinkenlifte Hallein / Bad Dürrnberg",
  "Mölltaler Gletscherbahnen & Ankogelbahn",
  "Lungau",
  "Hinterstoder / Wurzeralm",
  "Hochficht",
];

export const superSkiCardResortIds = [
  "kitzbuehel-kirchberg",
  "fieberbrunn",
  "alpbachtal",
  "brixen",
  "ellmau",
  "going",
  "hopfgarten",
  "scheffau",
  "soell",
  "westendorf",
  "gerlos",
  "zell-am-ziller",
  "gerlosstein",
];

export const snowCardTirolResorts = [
  "Alpbachtal - Ski Juwel Alpbachtal Wildschönau",
  "Amberglift Walchsee",
  "Axamer Lizum",
  "Bergbahnen Pillersee - Buchensteinwand - St. Ulrich",
  "Bergeralm",
  "Bergwelt Hahnenkamm",
  "Berwang",
  "Bichllifte Prägraten",
  "Brixen im Thale - SkiWelt",
  "Dorfberg Kartitsch",
  "Eggalmbahnen",
  "Ehrwalder Alm",
  "Ehrwalder Wettersteinbahnen",
  "Elferbahnen Neustift",
  "Ellmau-Going - SkiWelt",
  "Fendels - Ried - Prutz",
  "Finkenberger Almbahnen",
  "Fiss-Ladis",
  "Füssener Jöchle - Grän/Tannheimer Tal",
  "Galtür",
  "Gerlos - Zillertal Arena",
  "Gerlosstein - Zillertal Arena",
  "Glungezer",
  "Großglockner Resort Kals-Matrei",
  "Gschwandtkopflifte",
  "Hintertuxer Gletscher",
  "Hochalmlifte Christlum - Achenkirch",
  "Hochfügen",
  "Hochkrimml - Zillertal Arena",
  "Hochoetz - Oetz",
  "Hochzeiger - Jerzens",
  "Hochzeiger - Pitztal",
  "Hochzillertal-Kaltenbach",
  "Hopfgarten - Itter - SkiWelt",
  "Hüttegglift Weerberg",
  "Imst",
  "Ischgl - Silvretta Arena",
  "Kappl",
  "Karwendel-Bergbahn - Pertisau",
  "Katzenkopf Leutasch",
  "Kaunertaler Gletscher",
  "Kellerjochbahn Schwaz-Pill",
  "Kitzbühel",
  "Kolsassberg",
  "Königsleiten - Zillertal Arena",
  "Konradshüttle",
  "Kössen",
  "Kühtai",
  "Landeck - Zams - Fliess (Familienskigebiet Venet)",
  "Lermoos-Grubigstein",
  "Lienz Zettersfeld Hochstein",
  "Mayrhofen",
  "Mittersill - Paß Thurn - Kitzbühel",
  "Muttereralm - Nockspitzbahn",
  "Nauders",
  "Nesselwängle im Tannheimer Tal",
  "Neukirchen - Bramberg - Wildkogel",
  "Neunerköpfle - Tannheim",
  "Nordkette - Innsbruck",
  "Obergurgl-Hochgurgl",
  "Obertilliacher Bergbahnen",
  "Patscherkofel",
  "Pitztaler Gletscher - Rifflsee",
  "Rangger Köpfl",
  "Rastkogelbahnen",
  "Rofan Seilbahn - Maurach",
  "Rosshütte - Seefeld in Tirol",
  "Schattwald - Zöblen im Tannheimertal",
  "Scheffau - SkiWelt",
  "Schlick 2000",
  "Schneeberglifte Thiersee",
  "Schwannerlifte in Weerberg",
  "See i. Paznauntal",
  "Serfaus",
  "Serlesbahnen Mieders",
  "Skilifte Kirchdorf",
  "Skilifte Knittel",
  "Skilifte Lärchenhof",
  "Skizentrum Sillian/ Hochpustertal",
  "Skizentrum St. Jakob",
  "Sölden",
  "Söll - SkiWelt",
  "Spieljochbahn Fügen",
  "St. Johann in Tirol",
  "Steinplatte-Waidring",
  "Steinplatte-Winklmoosalm",
  "Stubaier Gletscher",
  "Tiroler Zugspitzbahn",
  "Tirolina - Ski-,Sport-, und Aktivberg Thiersee",
  "Umhausen",
  "Venter Seilbahnen",
  "Vögelsberg Aktivpark",
  "Westendorf - SkiWelt",
  "Wildschönau - Ski Juwel Alpbachtal Wildschönau",
  "Zahmer Kaiser - Walchsee",
  "Zell am Ziller - Zillertal Arena",
];

export const snowCardTirolResortIds = [
  "alpbachtal",
  "amberglift-walchsee",
  "axamer-lizum",
  "bergeralm",
  "hahnenkamm-hoefen-reutte",
  "berwang",
  "brixen",
  "dorfberglift-kartitsch",
  "eggalm-tux-lanersbach",
  "ehrwald",
  "wettersteinbahnen-ehrwald",
  "ellmau",
  "going",
  "fendels",
  "finkenberger-almbahnen",
  "serfaus-fiss-ladis",
  "gerlos",
  "gerlosstein",
  "glungezer",
  "kals-grossglockner",
  "hintertux",
  "christlum",
  "hochfuegen",
  "oetz-hochoetz",
  "hochzeiger",
  "hochzillertal",
  "hopfgarten",
  "silvretta-arena-ischgl-samnaun",
  "kappl",
  "karwendel-bergbahn-pertisau",
  "kaunertal",
  "kitzbuehel-kirchberg",
  "koessen",
  "kuehtai",
  "lermoos",
  "lienz",
  "mayrhofen",
  "nauders",
  "obergurgl-hochgurgl",
  "innsbruck-igls-patscherkofel",
  "pitztalergletscher",
  "rastkogel-tux-vorderlanersbach",
  "rofan",
  "schattwald-zoeblen",
  "scheffau",
  "schlick",
  "see",
  "sillian",
  "soelden",
  "soell",
  "stjohann-tirol",
  "stubaier-gletscher",
  "zugspitzbahn",
  "tirolina-aktivberg-thiersee",
  "niederthai-oetztal",
  "vent",
  "westendorf",
  "wildschoenau",
  "zell-am-ziller",
];
